#!/bin/bash

RUNCMD="mpiexec -np"
SERVER=/home/zouevan/soft/dataspaces-1.3.0/bin/dataspaces_server

WRITEPROC=64
STAGINGPROC=1
READPROC=1
let "PROCALL=WRITEPROC+READPROC"

# clean-up previous run
rm -f log.* core* conf dataspaces.conf
rm *staged.bp

# Prepare config file for DataSpaces
echo "## Config file for DataSpaces
ndim = 3
dimx = 400
dimy = 400
dimz = 400
max_versions = 10
#max_readers =" $READPROC "
#lock_type = 2
" > dataspaces.conf

# Run DataSpaces
echo "-- Start DataSpaces server "$SERVER" on $STAGINGPROC PEs, -s$STAGINGPROC -c$PROCALL"
$RUNCMD $STAGINGPROC $SERVER -s$STAGINGPROC -c$PROCALL &> log.server &

## Give some time for the servers to load and startup
sleep 1s
while [ ! -f conf ]; do
    echo "-- File conf is not yet available from server. Sleep more"
    sleep 1s
done
sleep 3s  # wait server to fill up the conf file

## Export the main server config to the environment
while read line; do
    export set "${line}"
done < conf

echo "-- DataSpaces IDs: P2TNID = $P2TNID   P2TPID = $P2TPID"

# Start GENARRAY
echo "-- Start GENARRAY on $WRITEPROC PEs"
mpiexec -machinefile host -n $WRITEPROC ./ccsm.exe >& log.licom &

# Start STAGE_WRITE
echo "-- Start STAGE_WRITE on $READPROC PEs"
$RUNCMD $READPROC ./staging 1 3000 1 1 1 >& log.staging &

echo "-- Wait until all applications exit. Run ./check.sh to see status"
wait
rm -f conf
